### PR TITLE
Improvements on Dutch translation

### PR DESCRIPTION
**Pull request by MadEgg**
This commit fixes a lot of spelling and grammar errors, removes incorrect spaces and unifies the translation of 'Contacts' that varied between 'contacten', 'mensen' en 'personen' while referring to the same thing.

### CODE REVIEW

**Comment by marcoconti83** [comment]
Hey @MadEgg , thanks for the contribution!
These files though are autogenerated from out crowd translation platform, so changes to the file will be overwritten in the next release. @teller @david-wire can you please advise on what's the proper way to make changes to the translation?

**Comment by MadEgg** [comment]
Crowd translation? Ouch. Sorry to say, based on the existing translation I was under the impression that it must've been done with Google Translate or like that. It does explain the variety in the translations of some words, but it doesn't explain why certain parts of sentences have not been translated (probably the translator didn't know the translation of a word in the sentence but translated the sentence nonetheless, just skipping over that word).

Anyway, I'm be totally happy entering the corrections elsewhere as I'd really like to see a proper Dutch translation. Especially the frequent showing of 'Anuleer' (Cancel) which is incorrect and should be 'Annuleer' is painful - most of the other texts don't show up that frequently in the app.

**Comment by teller** [comment]
Hi @MadEgg, we use Crowdin to manage the translations. You're more than welcome to join the project here: https://crowdin.com/projects/wire

Apologies for asking you to do double work…

**Comment by MadEgg** [comment]
No problem, it's probably just a bit of copy/paste. I submitted a request to join the translation team on CrowdIn.

Did I miss a mention on the website referring to CrowdIn / Crowd Translations, or is it not mentioned? If it's missing, then please consider adding a link and some text describing the translation process somewhere on the website.

**Pull request closed without merging**
