### PR TITLE
Attempt to fix TabBar crash, animate tabbar selection line

### PR DESCRIPTION
**Pull request by daehn**
## What's new in this PR?

* Attempt to fix `TabBar` crash.
* Animate `TabBar` selection indicator line when swiping.

### CODE REVIEW

**Comment by typfel** [comment]
Can you point out the crash fix?

**Comment by daehn** [comment]
It's the `Dispatch.main.async` as it seems this method isn't always called from the main thread, wasn't able to reproduce it though, will have to see if it still occurs in internal builds.

**Comment by typfel** [comment]
Ok, weird that it's not always called from the main thread though. I guess the real bug is somewhere else then.

**Comment by daehn** [comment]
@typfel yeah I am also not too happy with this workaround to be honest, not sure if it's worth it spending more time on this though (assuming this workaround actually fixes the crash for good).

**Comment by daehn** [comment]
Fixing snapshots.

**Pull request merged**
