### PR TITLE
Unread status dot to the back button

### PR DESCRIPTION
**Pull request by mikeger**
Inspired by @anatoli26
Thanks @Yorgos-V and @markesaaremets 

https://github.com/wireapp/wire-ios/issues/756

screen shot 2017-02-28 at 15 49 04

### CODE REVIEW

**Comment by typfel** [comment]
Is the button icon hooked up to a observer of the unread count?

**Comment by daehn** [comment]
@mikeger do we observe the conversation list to update this when receiving a message while in a different conversation?

**Comment by mikeger** [comment]
@typfel @daehn good point about possible incoming messages, I would need to add the observing

**Comment by mikeger** [comment]
@daehn @typfel updated, now with observer! I hope it would not make the whole app 2x slower 🐌

**Pull request merged**
