### PR TITLE
Enable test coverage

### PR DESCRIPTION
**Pull request by vytis**
### Issues

We have not tracked test coverage on UI project for some reasons that are now forgotten.

### Solutions

The changes needed to enable it are inside shared resources branch. This PR will not be merged, but is needed to test if everything works as expected on CI.

### CODE REVIEW

**Comment by mikeger** [comment]
@vytis so this can be merged now? The test coverage link is not generated in the PR, and also not visible [here](https://codecov.io/gh/wireapp/wire-ios), but I guess it would be when we merge?

**Comment by vytis** [comment]
No, this is a bit broken still and code coverage report is not generated. Looking at it now. We should see the usual comment here from Codecov.io when it is fixed!

**Comment by mikeger** [comment]
Good to go now?

**Comment by vytis** [comment]
just need to make sure it works on frameworks, basically need to wait until this is done - https://circleci.com/gh/wireapp/wire-ios-data-model/2101 🕐 🕚

**Pull request merged**
