### PR TITLE
fix: Remove uppercase from the placeholder in `MessageTextView`

### PR DESCRIPTION
**Pull request by agisilaos**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [ ] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

With this PR we remove the uppercase text transform from the placeholder in Message Text field and in addition to that we removed the expanded separator from `ConversationCellBurstTimestampView`

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by KaterinaWire — APPROVED** [review]

**Review by David-Henner — COMMENTED** [review]
Are we ok with the text being truncated? (it happens in several snapshots)

Screenshot 2022-11-04 at 10 34 51

**Comment by agisilaos** [comment]
@David-Henner Yeah bc we increased the font size of the text.

**Comment by David-Henner** [comment]
> @David-Henner Yeah because we increased the font size of the text.

Right, but shouldn't we at least make sure it's truncated right? like `self-deleting mess...` instead of the text being cut off a bit randomly?

**Comment by agisilaos** [comment]
An interesting idea. I will add it as a todo on the list I'm creating with the fixes we need to make after we finish with the project. But you're right we need to take that into consideration.

**Review by David-Henner — APPROVED** [review]

**Pull request merged**
