### PR TITLE
Adjust conversation margins

### PR DESCRIPTION
**Pull request by daehn**
# What's in this PR?

* Adjust conversation margins and reduce author image size.
* Delete & rerecord all snapshots to clean up.

### CODE REVIEW

**Comment by mikeger** [comment]
@daehn I see some system messages with the upper case in the screenshots. Would it be OK, or you would create another PR to make them lowercase (if it is the plan) ?

**Comment by daehn** [comment]
I will merge back develop, where they are lowercased already.

**Comment by daehn** [comment]
@mikeger updated!

**Comment by daehn** [comment]
@mikeger found one snapshot where the title is still uppercased, will check.

**Comment by daehn** [comment]
@mikeger updated (again)!

**Pull request merged**
