### PR TITLE
iPhone X margins

### PR DESCRIPTION
**Pull request by nicorsm**
## What's new in this PR?

Fixed some misalignments on iPhone X:

- bottom margin on Search Results View (shared by Start UI and Add Participants View Controllers)
- bottom margin on Share View Controller

### CODE REVIEW

**Comment by nicorsm** [comment]
@mikeger we're already using `KeyboardAvoidingViewController` with `ShareViewController`, but it's used to manage the bottom offset of the keyboard between Share View Controller and the Keyboard Avoiding controller. 
Here, I'm using the observer to adjust the bottom margin of the safe area, which should be = 0 when the keyboard is open. Since I need to handle this case, is there a way to avoid adding a second observer to do the same thing on a child view controller?

**Comment by nicorsm** [comment]
No problem 🙂

**Comment by mikeger** [comment]
@nicorsm can be merged now?

**Comment by nicorsm** [comment]
@mikeger still need to fix one little thing with Start UI.

**Pull request merged**
