### PR TITLE
[Chore] bump data-model

### PR DESCRIPTION
**Pull request by David-Henner**
## What's new in this PR?

bump to the data model version containing the fix for the app crashing on launch

### CODE REVIEW

**Comment by typfel** [comment]
Tests are ailing due to breaking changes in https://github.com/wireapp/wire-ios-data-model/pull/1089

**Comment by billypchan** [comment]
@David-Henner I will include the bump in another PR.

**Comment by billypchan** [comment]
This PR is no longer need but still can be merged.

**Review by billypchan — APPROVED** [review]

**Review by typfel — APPROVED** [review]

**Comment by typfel** [comment]
These changes already exists on develop so I suggest we close this PR.

**Pull request closed without merging**
