### PR TITLE
release 3.85

### PR DESCRIPTION
**Pull request by billypchan**
## What's new in this PR?

Undo wire-ios-request-strategy major update

### CODE REVIEW

**Comment by billypchan** [comment]
@typfel I will leave this PR open until the patch of `wire-ios-request-strategy` is done.

**Comment by typfel** [comment]
I guess we can close this now since https://github.com/wireapp/wire-ios-request-strategy/pull/320 is merged

**Comment by typfel** [comment]
@billypchan why did you merge this into 3.84? `release/3.84` is released so why are we modified the the release branch?

**Comment by billypchan** [comment]
@typfel the only change I made was the version number.

**Pull request merged**
