### PR TITLE
chore: Remove `teamCreation` flow from the UI Project IC-18

### PR DESCRIPTION
**Pull request by agisilaos**
<table>
<td>
  <a href="https://wearezeta.atlassian.net/browse/IC-18" title="IC-18" target="_blank">TaskIC-18</a>  Remove`teamCreation`  from the UI project
  </td></table>
  <br />
 

----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [x] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

With this PR we remove all the code from the UI project related to the `teamCreation`. Why? Because it's dead code, not being used anywhere. That also includes deleting tests and snapshot reference images.

----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by johnxnguyen — APPROVED** [review]
👍🏻

**Comment by KaterinaWire** [comment]
@agisilaos  I saw that you removed the strings from the `base Localizable.strings` file. Should we remove it from all Localizable files?

**Comment by agisilaos** [comment]
> @agisilaos I saw that you removed the strings from the `base Localizable.strings` file. Should we remove it from all Localizable files?

I think that will happen automatically when a new PR is going to be opened for the translations? Not sure. If that's not the case I can remove them myself.

**Comment by KaterinaWire** [comment]
> @KaterinaWire From what I understood that will happen automatically with a next Localization PR.
> 
> So this is I guess ready for a review and hopefully ready to be merged into develop

Why do you think it will happen automatically?

**Comment by agisilaos** [comment]
It happened automatically in this case: https://github.com/wireapp/wire-ios/pull/5688

When @johnxnguyen removed the phone login/sign up flow etc.

**Review by KaterinaWire — APPROVED** [review]

**Pull request merged**
