### PR TITLE
[Chore] Include fix for 1:1 connnection with self

### PR DESCRIPTION
**Pull request by typfel**
## What's new in this PR?

Bump components to include https://github.com/wireapp/wire-ios-sync-engine/pull/1375 and https://github.com/wireapp/wire-ios-data-model/pull/1107

### CODE REVIEW

**Review by KaterinaWire — APPROVED** [review]

**Comment by KaterinaWire** [comment]
@typfel I'm doing a major release here wireapp/wire-ios/pull/4821

**Review by billypchan — APPROVED** [review]

**Review by billypchan — COMMENTED** [review]
test failed

**Comment by typfel** [comment]
> test failed

`AppLockPresenterTests.testThatItVerifiesPasswordWithCorrectMessageWhenNeeded()`  timed out. I'll try restarting the tests.

**Comment by typfel** [comment]
Closing due to https://github.com/wireapp/wire-ios/pull/4821

**Pull request closed without merging**
