### PR TITLE
Use existing modal top bar component to ensure iPad bar has correct height

### PR DESCRIPTION
**Pull request by daehn**
# What's in this PR?

* Use existing `ModalTopBar` component to ensure the top bar in the `ReactionsListViewController` has the correct height on all devices.

### CODE REVIEW

**Comment by mikeger** [comment]
@daehn should the screenshot tests be updated?

**Comment by daehn** [comment]
@mikeger good point, on it.

**Comment by marcoconti83** [comment]
Is this for RC?

**Comment by daehn** [comment]
@marcoconti83 not necessarily, just a visual fix, could also go into `develop`

**Comment by daehn** [comment]
@mikeger updated, should change the base or are we putting it in the RC?

**Pull request merged**
