### PR TITLE
Usernames initial implementation

### PR DESCRIPTION
**Pull request by mikeger**
# Contains

- https://github.com/wireapp/wire-ios/pull/409 (already reviewed)
- Update for the new SE API

### CODE REVIEW

**Comment by daehn** [comment]
Actually I have a question, does this handle the case that a user might not have a handle?

**Comment by mikeger** [comment]
@daehn when it was implemented the working assumption was that everyone is going to have a username

**Comment by daehn** [comment]
@mikeger ok, I will have a look as we can't guarantee this anymore.

**Comment by daehn** [comment]
@mikeger please have a look at my last commit 161059b

**Pull request merged**
