### PR TITLE
Update renamed dependencies

### PR DESCRIPTION
**Pull request by typfel**
iOS repositories were renamed and update to the Cartfile is necessary to be able to fetch binaries.

### CODE REVIEW

**Comment by daehn** [comment]
Dependency cycle on `carthage bootstrap` on Travis

**Comment by typfel** [comment]
Yep, I guess we need to update all dependencies first.

**Comment by marcoconti83** [comment]
All dependencies should be updated already, other than `wire-ios-syncengine`

**Comment by typfel** [comment]
Ok, I'm updating `wire-ios-sync-engine`

**Comment by daehn** [comment]
Travis reports success but the tests never ran 🤔

**Comment by typfel** [comment]
Hmm... I'll restart

**Pull request merged**
