### PR TITLE
[Feature]: Analytics add UserID

### PR DESCRIPTION
**Pull request by marcomaddy1982**
## What's new in this PR?

in order to identify an user on Analytics we added an unique id in core data for the User object and set as value in the "user_id" of the Analytics userProperties.

### Dependencies

JIRA: https://wearezeta.atlassian.net/browse/ZIOS-13750

### CODE REVIEW

**Review by johnxnguyen — CHANGES_REQUESTED** [review]
Don't forget to bump the data model component.

**Review by billypchan — APPROVED** [review]

**Comment by billypchan** [comment]
@marcoconti83 You may also need to bump Sync engine since UI project links to data modal via Sync engine.

**Review by billypchan — CHANGES_REQUESTED** [review]
bump sync engine and check the tests would pass or not.

**Comment by marcomaddy1982** [comment]
> Don't forget to bump the data model component.

Done

**Comment by marcomaddy1982** [comment]
> bump sync engine and check the tests would pass or not.

I guess this is not necessary for now,  cause the data-model dependency is pointing to feature/Analytics?

**Pull request merged**
