### PR TITLE
resume Music playback after audio message completed playback.

### PR DESCRIPTION
**Pull request by billypchan**
Tested with iOS Music app and confirmed issue is fixed.
(Spotify can not be resumed)

### CODE REVIEW

**Comment by typfel** [comment]
Let's sync up with the AVS team on these changes because they are controlling the audio category in our app.

**Comment by mikeger** [comment]
Hey @z-dule , can you comment on this? Should we do it here for audio messages?

**Comment by z-dule** [comment]
Please do not control the active state or the category outside of the mediamanager, doing so will break the purpose of the MediaManager.

**Comment by mikeger** [comment]
@z-dule @typfel  should we (or are we already) tell mediamanger that we are about to play / finished playing the audio message?

**Comment by z-dule** [comment]
@mikeger don't you already play the sound through the MediaManager?

**Comment by mikeger** [comment]
As a matter of fact we do, through `MediaPlaybackManager`

**Comment by mikeger** [comment]
@billypchan sorry for the confusion, @z-dule is going to take care of this case via AVS MediaManager.

**Pull request closed without merging**
