### PR TITLE
Fix/zios 9227 replace is ipad macro

### PR DESCRIPTION
**Pull request by billypchan**
replace all IS_IPAD macros and UIDevice currentDevice].userInterfaceIdiom == UIUserInterfaceIdiomPad with Swift 

tested the UI appearance of ParticipantsHeaderView, fixed the issue cancel button is not shown in slide over mode.

### CODE REVIEW

**Comment by mikeger** [comment]
@billypchan All the code that is checking if it's an iPad is not entirely aligned with the guidelines, since according to Apple we should be good with the size class. Most of this code as you see is in Objective-C. It is because we decided not to port the old code to the new system. In the new swift code we try not to rely on the fact that we are working on the iPad. We should not rely on iPad / not-iPad logic looking forward, therefore I would prefer not to expose the `SizeClass` class to Swift/new code since someone can think that it is acceptable to use it.

**Comment by mikeger** [comment]
In quite some places you are changing the logic from IS_IPAD to check also the full screen mode, have you tested all the cases changed?

**Comment by billypchan** [comment]
@mikeger Thanks. I will rewrite it as a macro. This PR is focus on ParticipantsHeaderView and MagicConfig. More minor issues is WIP.

**Comment by mikeger** [comment]
@billypchan I think it's OK for it to be a method, may be just port it to Obj-C. Thanks!

**Comment by billypchan** [comment]
@mikeger I will separate the logics of "which kind of device" and "what kind of size class" into two parts in next PR.

**Pull request merged**
