### PR TITLE
Clean up objc related setting in share extension target

### PR DESCRIPTION
**Pull request by billypchan**
## What's new in this PR?

remove objc related setting in share extension target.

### TODO
- [x] define these in .xcconfig after UI project has no objc code.

### CODE REVIEW

**Comment by johnxnguyen** [comment]
How long until the UI project is Objc free?

**Comment by billypchan** [comment]
@johnxnguyen there should be one more PR to clean up .h and .m files.

**Comment by johnxnguyen** [comment]
So maybe we should clean up the .h and .m files first, then we can add these settings to .xcconfig

**Comment by billypchan** [comment]
@johnxnguyen I undo the project file and will change it in a new PR.

**Pull request merged**
