### PR TITLE
feat: fix network status view background fix - ACC - 278

### PR DESCRIPTION
**Pull request by BrzozowskiPawel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [ ] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR I have fixed the issue with the wrong background color for the network status. Before this fix there was no color so it looked wrong in comparison to the top bar. Now it's blending in.

**OLD**:
Old

**NEW**:
New

----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by KaterinaWire — APPROVED** [review]

**Comment by KaterinaWire** [comment]
@BrzozowskiPawel There are failed tests

**Comment by BrzozowskiPawel** [comment]
@KaterinaWire I have pushed the fix.

**Comment by BrzozowskiPawel** [comment]
I don't have any idea why it failed. 
**Steps that I have done**: 
- run all the tests
- in the setup after super.setup add recordMode = true (to the class that fails)
- run all the tests again
- delete recordMode = true
- run the tests (all passes)
- push the changes

**Comment by KaterinaWire** [comment]
> I don't have any idea why it failed. **Steps that I have done**:
> 
> * run all the tests
> * in the setup after super.setup add recordMode = true (to the class that fails)
> * run all the tests again
> * delete recordMode = true
> * run the tests (all passes)
> * push the changes

NetworkStatusViewControllerSnapshotTests.testOnlineSynchronizing is failed

**Comment by BrzozowskiPawel** [comment]
> > I don't have any idea why it failed. **Steps that I have done**:
> > 
> > * run all the tests
> > * in the setup after super.setup add recordMode = true (to the class that fails)
> > * run all the tests again
> > * delete recordMode = true
> > * run the tests (all passes)
> > * push the changes
> 
> @BrzozowskiPawel NetworkStatusViewControllerSnapshotTests.testOnlineSynchronizing is failed. Check this test

Yes, but it seems that it's passing here:
image

**Comment by agisilaos** [comment]
@KaterinaWire & @BrzozowskiPawel I will take a look on the tests in a bit. Don't push anything in the meantime please.

**Pull request closed without merging**
