### PR TITLE
Flood conversation with messages (debug)

### PR DESCRIPTION
**Pull request by mikeger**
### Issues

The option to append 10.000 text messages to the conversation. The messages are not scheduled for sending.

### Causes

This is necessary for testing the performance and the backup-restore scenarios.

### CODE REVIEW

**Comment by vytis** [comment]
I am just not sure if it saves every time we append the message. Maybe it would be faster to do it on the sync thread inside a grouped block?

**Comment by mikeger** [comment]
Good point, I will check in the profiler what is the best way to schedule the insertions.

**Comment by vytis** [comment]
@mikeger What do we need to merge this one?

**Comment by mikeger** [comment]
I need some time to make sure this works in the best possible way in regards of performance.

**Comment by mikeger** [comment]
@vytis I've optimized the appending of the messages, the single potential problem left is when I save the context, the change notification is really huge and takes a long time to process, haven't figured out the way around it.

**Pull request merged**
