### PR TITLE
fix offset

### PR DESCRIPTION
**Pull request by wujichao**

### CODE REVIEW

**Comment by marcoconti83** [comment]
Thank you @wujichao for taking the time to look at our code! 

Can you please add some context for this pull request? What issue is it addressing?

**Comment by mikeger** [comment]
@marcoconti83 I believe we had a bug in offset calculation. `StackView` supports stacking subviews vertically or horizontally. However it seems that there was a bug that we where only correctly calculated the view positions for horizontal layout.

@wujichao Thanks for the contribution, right now we are in process of preparing the legal framework for third parties contribution, we'll notify you when it would be possible to merge your PR.

**Comment by wujichao** [comment]
@marcoconti83 Hi, when stackView used with direction equals to StackViewDirectionVertical, the offset should be heights of subviews plus spaces.  Sorry I am good at english, do you understand what i said? if needed i will upload a demo for this.

**Comment by wujichao** [comment]
@mikeger  Thank you, you just described what i want to describe :)

**Comment by marcoconti83** [comment]
Thanks again for taking the time to make this PR, @wujichao !

Before we can accept your pull request you need to sign our contributor agreement for legal reasons. Please follow the steps outlined here: https://github.com/wireapp/wire#contributions and let us know if you have any issues with that!

**Comment by david-wire** [comment]
We received @wujichao's WCA and can go ahead with the PR.

**Pull request merged**
