### PR TITLE
Self deleting messages (part 1)

### PR DESCRIPTION
**Pull request by johnxnguyen**
## What's new in this PR?

**Jira:** https://wearezeta.atlassian.net/browse/SQSERVICES-541

This PR contains api changes introduced in https://github.com/wireapp/wire-ios-data-model/pull/1229.

### CODE REVIEW

**Review by billypchan — APPROVED** [review]

**Review by billypchan — CHANGES_REQUESTED** [review]
build failed for 
`❌  /Users/runner/work/1/s/Wire-iOS Tests/Mocks/MockConversation.swift:71:13: type 'MockGroupDetailsConversation' does not conform to protocol 'GroupDetailsConversation'

final class MockGroupDetailsConversation: SwiftMockConversation, GroupDetailsConversation {
            ^
`

**Comment by KaterinaWire** [comment]
@johnxnguyen There are `SwiftLint` warnings.

**Comment by KaterinaWire** [comment]
It would be nice to have tests when the feature is enforced by the team admin.

**Comment by johnxnguyen** [comment]
@KaterinaWire I fixed the issues and added tests.

**Review by billypchan — APPROVED** [review]

**Review by KaterinaWire — APPROVED** [review]

**Pull request merged**
