### PR TITLE
Feature: display iOS 13 link context menu when long press on a link

### PR DESCRIPTION
**Pull request by billypchan**
## What's new in this PR?

Display the iOS link context when long press on a link.
Markdown link is excluded for long tap context menu.

### snapshots: 

detected link:

context menu when long press on the link:

### CODE REVIEW

**Comment by billypchan** [comment]
@johnxnguyen tested with markdown link and it also works.

**Comment by johnxnguyen** [comment]
> @johnxnguyen tested with markdown link and it also works.

What do you mean by it works? Does it show the preview? Because the expected behavior is to show an popup asking the user if they want to visit the url.

**Comment by billypchan** [comment]
@johnxnguyen the behavior of tapping on a markdown link is:
normal tap: show the external link alert
long tap: show the context menu with preview (The user can tap the domain name and choose open it or not)

**Comment by johnxnguyen** [comment]
If I remember correctly, the behavior with force touch peeking was that it should also show the confirmation alert. In my opinion, the long tap should behave just like the force touch gesture.

**Review by watcher699 — COMMENTED** [review]
Good

**Review by watcher699 — COMMENTED** [review]
Good

**Pull request merged**
