### PR TITLE
Giphy optimization comparison: .gif vs .mp4

### PR DESCRIPTION
**Pull request by vorobievalex**
This is not to be merged and to be closed after the discussion is over. These are draft changes, switching trending Giphy screen from gif to mp4 videos format.
The aim of this discussion is to provide details for the format selection.

Below are the main metrics of .gif and .mp4 formats rendering for Giphy trending screen.

> giphy.com does not provide a downsampled version in mp4 format, so this compares two gif optimizations:
> - existing downsampled 200px-width `gif` files rendering
> - `mp4` compressed 200px-width files rendering
> Results are for a random set of videos, so would vary for different runs.

1. Total download size for 50 top trending images - for mp4 is 7% less than for gif:
```
Sum of 50 downsampled gifs: 4278578 bytes
Sum of 50 mp4s:             3965420 bytes
```
The reason is that mp4 compression sometimes gives less effect than gif downsampling.

<details/>
 <summary>Files sizes from trending son results printed to log</summary>
Output of https://github.com/vorobievalex/wire-ios-ziphy/blob/7327d1c2f6ae90237c4e66afa56b49ae9aa8dbeb/ziphy/ZiphyClient.swift#L302-L319

```
fixed_width gif size: 809387
fixed_width mp4 size: 156454
fixed_width_downsampled gif size: 71639
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 982026
fixed_width mp4 size: 185531
fixed_width_downsampled gif size: 95786
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 865050
fixed_width mp4 size: 228042
fixed_width_downsampled gif size: 102745
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 54060
fixed_width mp4 size: 21219
fixed_width_downsampled gif size: 23666
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 278772
fixed_width mp4 size: 101763
fixed_width_downsampled gif size: 105371
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 302203
fixed_width mp4 size: 86106
fixed_width_downsampled gif size: 39626
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 23902
fixed_width mp4 size: 11654
fixed_width_downsampled gif size: 23902
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 565549
fixed_width mp4 size: 115813
fixed_width_downsampled gif size: 92617
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 459311
fixed_width mp4 size: 55209
fixed_width_downsampled gif size: 75482
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 387275
fixed_width mp4 size: 41812
fixed_width_downsampled gif size: 83763
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 1510035
fixed_width mp4 size: 116570
fixed_width_downsampled gif size: 110441
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 932074
fixed_width mp4 size: 70059
fixed_width_downsampled gif size: 134547
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 299583
fixed_width mp4 size: 58097
fixed_width_downsampled gif size: 132222
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 10998
fixed_width mp4 size: 10774
fixed_width_downsampled gif size: 6518
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 487420
fixed_width mp4 size: 52885
fixed_width_downsampled gif size: 129229
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 184752
fixed_width mp4 size: 24127
fixed_width_downsampled gif size: 77459
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 152797
fixed_width mp4 size: 77646
fixed_width_downsampled gif size: 12745
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 708675
fixed_width mp4 size: 46923
fixed_width_downsampled gif size: 81864
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 719543
fixed_width mp4 size: 187452
fixed_width_downsampled gif size: 48009
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 407444
fixed_width mp4 size: 71186
fixed_width_downsampled gif size: 70296
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 988546
fixed_width mp4 size: 160214
fixed_width_downsampled gif size: 97347
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 978068
fixed_width mp4 size: 104712
fixed_width_downsampled gif size: 110176
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 478899
fixed_width mp4 size: 59340
fixed_width_downsampled gif size: 78670
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 530529
fixed_width mp4 size: 85250
fixed_width_downsampled gif size: 51485
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 1720345
fixed_width mp4 size: 434436
fixed_width_downsampled gif size: 147347
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 54343
fixed_width mp4 size: 21220
fixed_width_downsampled gif size: 54343
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 25159
fixed_width mp4 size: 11390
fixed_width_downsampled gif size: 82143
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 45772
fixed_width mp4 size: 32479
fixed_width_downsampled gif size: 120977
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 75878
fixed_width mp4 size: 14394
fixed_width_downsampled gif size: 149687
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 97640
fixed_width mp4 size: 13727
fixed_width_downsampled gif size: 101395
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 540608
fixed_width mp4 size: 44656
fixed_width_downsampled gif size: 131348
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 2012231
fixed_width mp4 size: 173240
fixed_width_downsampled gif size: 126975
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 93814
fixed_width mp4 size: 22015
fixed_width_downsampled gif size: 63342
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 584791
fixed_width mp4 size: 250153
fixed_width_downsampled gif size: 92662
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 19012
fixed_width mp4 size: 15060
fixed_width_downsampled gif size: 16727
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 103640
fixed_width mp4 size: 23446
fixed_width_downsampled gif size: 103640
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 443566
fixed_width mp4 size: 53748
fixed_width_downsampled gif size: 91817
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 26355
fixed_width mp4 size: 10940
fixed_width_downsampled gif size: 22499
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 56820
fixed_width mp4 size: 25183
fixed_width_downsampled gif size: 43593
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 126208
fixed_width mp4 size: 39595
fixed_width_downsampled gif size: 38102
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 571669
fixed_width mp4 size: 93011
fixed_width_downsampled gif size: 121148
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 225459
fixed_width mp4 size: 34719
fixed_width_downsampled gif size: 62214
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 508648
fixed_width mp4 size: 85494
fixed_width_downsampled gif size: 115223
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 276343
fixed_width mp4 size: 48804
fixed_width_downsampled gif size: 122834
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 900930
fixed_width mp4 size: 125003
fixed_width_downsampled gif size: 103872
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 357218
fixed_width mp4 size: 36792
fixed_width_downsampled gif size: 141677
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 445181
fixed_width mp4 size: 115424
fixed_width_downsampled gif size: 65368
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 373656
fixed_width mp4 size: 35265
fixed_width_downsampled gif size: 103491
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 223139
fixed_width mp4 size: 15958
fixed_width_downsampled gif size: 98424
fixed_width_downsampled mp4 size: NA


fixed_width gif size: 469334
fixed_width mp4 size: 60430
fixed_width_downsampled gif size: 102125
fixed_width_downsampled mp4 size: NA


mp4 total: 3965420
gif total: 4278578
```
</details>
<br/>
2. Processors utilization while rendering 12 first trending results. mp4 rendering uses processors for a longer time at 80%. Gig rendering uses 20% for a short time.

So, mp4 decompression loads processors a lot.

<details/>
 <summary>CPU debugger screenshots</summary>

gif:
Image of processor usage to display gif
mp4:
Image of processor usage to display mp4
</details>

3. Memory usage while rendering 12 first trending results - 270 MB for mp4 vs 7 MB for gif.

4. Delay before all the 12 pictures appear on the screen is about the same - 5 seconds.

Tested at iPhone7 iOS 11.0.1.

### CODE REVIEW

**Comment by billypchan** [comment]
Hi vorobievalex, thanks for your detailed study. I will try your PR on iPad also to study the CPU and memory usage.

**Comment by mikeger** [comment]
Hey @vorobievalex ! Thanks for the effort, once again a great contribution. I'll check the numbers, but from what you are explaining it seems that it's better to stay with GIFs.

**Comment by billypchan** [comment]
@vorobievalex, I tried you PR on iPad Pro with some rewrite for loading video in background thread. Theoretically embedding an AVPlayer should work but:
- Scrolling the collection view is not as smooth as with  GIF cells, since loading an AVPlayerItem is heavy task and it take time to finish loading and it has to occupy main thread in some points. 
- It seems like iOS has limitation for the number of AVPlayer can start playing at the same time. On device test I found the limit is around 8~12 on iPad Pro. 

I suggest we should stay with GIF, may be try to use better quality one(2 stage loading). Or may be looking for a good WebP library?

**Comment by vorobievalex** [comment]
Hi @ billypchan, @mikeger. I could try WebP, but per Google faq here:
https://developers.google.com/speed/webp/faq#why_should_i_use_animated_webp
WebP is more CPU-intensive than GIF - 15x/2.2x much time to decode.
At the same time the advantages listed in the same faq seem not to give much in this use case - 19% less size only.

2 stage loading of git  is a great idea. Giphy search screen currently takes seconds to load.
Use of the additional loading stage will use more network and CPU in total, but the result might worth it. What do you think?

**Comment by mikeger** [comment]
@vorobievalex sounds interesting, thanks for the research, once again a great contribution. I was thinking to approach the problem from another angle. Original idea was that mp4s are going to have the size/performance advantage, which does not seem to be true. So let's scratch this part for the moment.

I think currently one of the issues is that user actually sees way too many GIFs (especially on iPad) at once. May be it would be better to have the GIF keyboard? Then we can put the GIFs in the row. It should be fairly easy to implement, since we have a pretty general implementation of the camera roll keyboard. What would you think?

**Comment by vorobievalex** [comment]
Agree, a keyboard will look nicer. I shall try it.

**Comment by mikeger** [comment]
@vorobievalex we are testing internally with @billypchan and it seems like webP is doing the job quite nicely on the CPU side, we'll continue investigating it there.

**Comment by billypchan** [comment]
@vorobievalex You may check out:
 https://github.com/billypchan/wire-ios-ziphy/tree/feature/webp
for my draft work for replace GIF with webP.

Things to thing about:
- Should we include a still low quality image for each Giphy?
- Main Thread sometimes hit 100% when fast scrolling down. In average CPU usage is over 50%.

**Comment by vorobievalex** [comment]
In practice webp is impressing. For the first several pages of giphy.com it gives more than 2x compression - around 1.8MB instead of 4.4MB.

Decoding takes more CPU, but webp requires less energy to download and less time to draw the search screen. So webp looks like the winner here.

@billypchan, I did try your changes, but with downsampled webp mages. CPU peak was at 40%, but it less time than it was at gif screen above. So it looks similar to theoretical 1.5x CPU usage increase.
screen shot 2017-12-22 at 3 11 14 pm

**Comment by vorobievalex** [comment]
@billypchan, additional stage with still low quality images is a great idea. It can be used with the both gif and webp. So this can be a separate proposal.

**Comment by vytis** [comment]
I am closing this PR as it was not meant to be merged! Thanks again for looking into this, we will see what could be done further to make it work nicely.

**Pull request closed without merging**
