### PR TITLE
[Feature] active speaker frame

### PR DESCRIPTION
**Pull request by David-Henner**
## What's new in this PR?

- Show a border around the video tile when the video participant is actively speaking

### CODE REVIEW

**Review by billypchan — APPROVED** [review]
It would be better to create a snapshot for this change.

**Comment by David-Henner** [comment]
> It would be better to create a snapshot for this change.

I've created one, but I think that GitHub is not rendering it. You can find it [there](https://github.com/wireapp/wire-ios/blob/32f60ffb5df066025cab4d236b89d6f3f4596ba7/Wire-iOS%20Tests/ReferenceImages/VideoPreviewViewTests/testActiveState.1.png)

**Comment by KaterinaWire** [comment]
Do we have tests for active speaker?

**Comment by David-Henner** [comment]
> Do we have tests for active speaker?

There's a snapshot test [here](https://github.com/wireapp/wire-ios/blob/32f60ffb5df066025cab4d236b89d6f3f4596ba7/Wire-iOS%20Tests/ReferenceImages/VideoPreviewViewTests/testActiveState.1.png)

**Review by KaterinaWire — APPROVED** [review]

**Comment by KaterinaWire** [comment]
> > Do we have tests for active speaker?
> 
> There's a snapshot test [here](https://github.com/wireapp/wire-ios/blob/32f60ffb5df066025cab4d236b89d6f3f4596ba7/Wire-iOS%20Tests/ReferenceImages/VideoPreviewViewTests/testActiveState.1.png)

I approved

**Pull request merged**
