### PR TITLE
Fix/conversation list resorting

### PR DESCRIPTION
**Pull request by marcoconti83**
# Reason for this pull request
Keep conversation list in order after coming to foreground

### CODE REVIEW

**Comment by marcoconti83** [comment]
⚠️ Found issue, do not merge ⚠️

**Comment by typfel** [comment]
@marcoconti83  so we can close this?

**Comment by marcoconti83** [comment]
So this can be merged. We will need then to test in develop build with the new data model framework to confirm that it fixes the issue. It's not easy to test.

**Comment by typfel** [comment]
Oh I thought it would all be handled from SE side.

**Comment by marcoconti83** [comment]
This was also addressed not on sync engine but on data model. So now in data model we resort the list when we are flushing the accumulate changes (basically when we go back to live processing of changes). 
However I would like to leave a "refresh view" in the UI (no resorting, the underlying list should be resorted by data model already), which if I understood correctly causes the entire UI view to be reloaded from the underlying list (which now should already be resorted by data model).
As I mentioned this issue is not easy to reproduce (it requires leaving the phone alone for a few hours) so better to add a bit more extra safety and then see how it behaves on real device.

**Comment by marcoconti83** [comment]
@typfel any further thought on this?

**Comment by typfel** [comment]
No but would nice to clean this up later if we refactor the observation

**Pull request merged**
