### PR TITLE
feat: loading background update to match figma design - ACC - 276

### PR DESCRIPTION
**Pull request by BrzozowskiPawel**
----
#### PR Submission Checklist for internal contributors

- The **PR Title**
  - [x] conforms to the style of semantic commits messages¹ supported in Wire's Github Workflow²
  - [x] contains a reference JIRA issue number like `SQPIT-764`
  - [ ] answers the question: _If merged, this PR will: ..._ ³

- The **PR Description**
  - [x] is free of optional paragraphs and you have filled the relevant parts to the best of your ability
----

# What's new in this PR?

In this PR I have fixed the loading screen's background for displaying when you add an account and abort it by pressing the close button. 
Previously background was showing a blurred image and now it's default background solid color.

Graphic representation: 
**OLD dark**:
Old-Dark
**OLD light**:
Old-light
---
**NEW dark**: 
New - dark
**NEW light**:
New - light 
---
</br>
----
#### PR Post Submission Checklist for internal contributors (Optional)

 - [x] Wire's Github Workflow has automatically linked the PR to a JIRA issue
----
#### PR Post Merge Checklist for internal contributors

 - [ ] If any soft of configuration variable was introduced by this PR, it has been added to the relevant documents and the CI jobs have been updated.
----
##### References
1. https://sparkbox.com/foundry/semantic_commit_messages
1. https://github.com/wireapp/.github#usage
1. E.g. `feat(conversation-list): Sort conversations by most emojis in the title #SQPIT-764`.

### CODE REVIEW

**Review by agisilaos — COMMENTED** [review]
I'm not sure we need the buttonRowView since the design for the button row changed. Any thoughts, @KaterinaWire?

**Comment by BrzozowskiPawel** [comment]
@agisilaos good call. Let's wait for Katerina's answer and I will match code to it.

**Review by KaterinaWire — APPROVED** [review]

**Comment by KaterinaWire** [comment]
> @agisilaos good call. Let's wait for Katerina's answer and I will match code to it.

@BrzozowskiPawel @agisilaos I think we can continue with this solution

**Review by agisilaos — APPROVED** [review]

**Comment by agisilaos** [comment]
Let's merge it as it is.

**Pull request merged**
