### PR TITLE
Fix: Call screen is not presented when call quality screen is dismissing

### PR DESCRIPTION
**Pull request by billypchan**
### Issues

When a call quality screen is presented and a new incoming call is ringing, the call screen does not present, tap on the top bar does not open the call screen.

### Causes

The dismissal of the call quality screen and the presenting of the call screen starts at the same time and the later one fails to complete.

### Solutions

Delay the presenting of the call screen in this case.

### CODE REVIEW

**Comment by billypchan** [comment]
@johnxnguyen I also thought about that. The problem is the dismissal and presenting are trigged from 2 parts of the project( `CallQualityController` and `CallController`) and triggered by the same observer event. The presenting and the dismissal are not always happens at the same time.

**Comment by johnxnguyen** [comment]
Is the calling survey actually doing anything anymore?

**Comment by billypchan** [comment]
Yes, calling survey is still in use.

**Comment by johnxnguyen** [comment]
> @johnxnguyen I also thought about that. The problem is the dismissal and presenting are trigged from 2 parts of the project( CallQualityController and CallController) and triggered by the same observer event. The presenting and the dismissal are not always happens at the same time.

Isn't the `CallQualitiyController` asking its delegate (`CallQualityController`) to dismiss the survey?

Perhaps we could make only the `CallQualityController` do the dismissal within the `presentCall` method, so we could use the completion handler?

**Comment by billypchan** [comment]
@johnxnguyen rewrite as your suggestion.

**Pull request merged**
