### PR TITLE
Add input bar send and emoji button improvements

### PR DESCRIPTION
**Pull request by daehn**
# What's in this PR?

* Align emoji and send button sticky to the bottom instead of to the top of the input bar.
* Increase the hit area of the send button to the right.

### CODE REVIEW

**Comment by mikeger** [comment]
Screenshots where not changed?

**Comment by daehn** [comment]
@mikeger we should add a `Danger` rule that checks "if any of the modified files contains a UIView subclass and there are no snapshot tests added or changed leave a comment on the PR"

**Comment by daehn** [comment]
@mikeger please re-review

**Comment by daehn** [comment]
This fixes https://github.com/wireapp/wire-ios/issues/332

**Pull request merged**
